# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'drinkassist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for drinkassist

pod 'Firebase/Core'
pod 'Firebase/Database’
pod 'Firebase/Storage'
pod 'Firebase/AdMob'
pod 'Firebase/Messaging'
pod 'FacebookSDK'
pod 'lottie-ios'

end
